# ------------------------------------------------------------------------------
# DEV KAFKA
# ------------------------------------------------------------------------------
--- !!dev.north.fortyone.gradle.intellij.run.generator.models.ApplicationRunConfig
name: BESU | Dev | Kafka > Run
filename: BESU__Dev__Kafka__Run.xml
default: false
mainClassName: org.hyperledger.besu.Besu
module: exflo.ingestion.kafka.main
envs:
  BESU_SYNC_MODE: FULL
  BESU_LOGGING: INFO
  BESU_P2P_ENABLED: 'false'
  BESU_RPC_WS_ENABLED: 'true'
  BESU_RPC_HTTP_ENABLED: 'true'
  BESU_RPC_HTTP_API: eth,net,web3,admin,debug
  BESU_NETWORK: DEV
  BESU_DATA_PATH: "/opt/besu/dev"
  BESU_MINER_ENABLED: 'true'
  BESU_MINER_COINBASE: '0xf17f52151EbEF6C7334FAD080c5704D77216b732'
  BESU_PLUGIN_EXFLO_KAFKA_ENABLED: 'true'

# ------------------------------------------------------------------------------
# DEV POSTGRES
# ------------------------------------------------------------------------------
--- !!dev.north.fortyone.gradle.intellij.run.generator.models.ApplicationRunConfig
name: BESU | Dev | Postgres > Run
filename: BESU__Dev__Postgres__Run.xml
default: false
mainClassName: org.hyperledger.besu.Besu
module: exflo.ingestion.postgres.main
envs:
  BESU_SYNC_MODE: FULL
  BESU_LOGGING: INFO
  BESU_P2P_ENABLED: 'false'
  BESU_RPC_WS_ENABLED: 'true'
  BESU_RPC_HTTP_ENABLED: 'true'
  BESU_RPC_HTTP_API: eth,net,web3,admin,debug
  BESU_NETWORK: DEV
  BESU_DATA_PATH: "/opt/besu/dev"
  BESU_MINER_ENABLED: 'true'
  BESU_MINER_COINBASE: '0xf17f52151EbEF6C7334FAD080c5704D77216b732'
  BESU_PLUGIN_EXFLO_POSTGRES_ENABLED: 'true'
