--- !!dev.north.fortyone.gradle.intellij.run.generator.models.GradleRunConfig
name: GRADLE | Ktlint > Format
filename: GRADLE__Ktlint__Format.xml
default: false
tasks:
  - ktlintFormat

--- !!dev.north.fortyone.gradle.intellij.run.generator.models.GradleRunConfig
name: GRADLE | Postgres > FlywayClean
filename: GRADLE__Postgres__FlywayClean.xml
default: false
tasks:
  - flywayClean
